<a href="https://colab.research.google.com/github/nhongtat-a11y/codefinity-deep-learning-with-tensorflow/blob/master/Practise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
# create 6 x 8 tensor with random values between 0 and 1

In [4]:
random_tensor = torch.rand(6, 8)
print(random_tensor)

tensor([[0.0807, 0.9154, 0.8601, 0.5504, 0.8846, 0.9027, 0.3874, 0.9388],
        [0.9354, 0.3637, 0.7765, 0.3353, 0.9516, 0.8401, 0.2110, 0.3012],
        [0.4572, 0.2334, 0.9534, 0.0207, 0.6474, 0.6758, 0.1495, 0.1447],
        [0.9232, 0.0704, 0.1998, 0.8017, 0.7402, 0.5409, 0.5860, 0.2910],
        [0.8913, 0.4593, 0.4966, 0.1136, 0.8293, 0.8752, 0.0861, 0.3084],
        [0.7242, 0.8409, 0.3736, 0.7914, 0.6229, 0.9342, 0.6592, 0.3896]])


In [6]:
normal_tensor = torch.randn(6,8)
print(normal_tensor)

tensor([[-0.2348,  0.9500, -0.1110, -0.0355,  0.2932, -0.5712, -2.2112,  0.6301],
        [-0.9399, -0.1887,  0.8163,  0.8216,  0.6653, -0.4098,  0.8847, -1.5117],
        [-0.0274,  1.6678, -1.9453,  0.3850, -1.9984, -0.0375,  1.5247, -0.2542],
        [-0.9539, -0.2922, -0.8189, -0.2683,  0.3123,  0.9536, -1.1337, -0.4423],
        [-0.3290, -0.5410, -0.4324, -0.9143, -0.7089,  0.9256, -1.3396, -1.9159],
        [-0.0798, -1.1888, -1.4178,  1.4241, -0.6412,  0.4558,  0.6800,  0.8090]])


In [7]:
# create 4x3 tensor with random integer between 0 and 10
integer_tensor = torch.randint(0, 10, (4,3))
print(integer_tensor)

tensor([[6, 6, 9],
        [9, 4, 3],
        [3, 8, 8],
        [9, 3, 9]])
